const INCREAMENT_ACC = "account/INCREAMENT_ACC";
const DECREAMENT_ACC = "account/DECREAMENT_ACC";
const INCREAMENT_BY_VALUE = "account/INCREAMENT_BY_VALUE";
const DECREAMENT_BY_VALUE = "account/DECREAMENT_BY_VALUE";
const FETCH_ACC_FULLFILLED = "account/FETCH_ACC_FULLFILLED";
const FETCH_ACC_PENDING = "account/FETCH_ACC_PENDING";
const FETCH_ACC_REJECTED = "account/FETCH_ACC_REJECTED";

const INCREAMENT_BONUS = "bonus/INCREAMENT_BONUS";

export {
  INCREAMENT_ACC,
  DECREAMENT_ACC,
  INCREAMENT_BONUS,
  INCREAMENT_BY_VALUE,
  FETCH_ACC_FULLFILLED,
  FETCH_ACC_PENDING,
  FETCH_ACC_REJECTED,
  DECREAMENT_BY_VALUE,
};
