const INCREAMENT_ACC = "account/INCREAMENT_ACC";
const DECREAMENT_ACC = "account/DECREAMENT_ACC";

const INCREAMENT_BONUS = "account/INCREAMENT_BONUS";
const DECREAMENT_BONUS = "account/DECREAMENT_BONUS";

export { INCREAMENT_ACC, DECREAMENT_ACC, INCREAMENT_BONUS, DECREAMENT_BONUS };
